# Generated by Django 2.2.6 on 2019-10-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='AuthorsModel',
        ),
    ]
