# Generated by Django 2.2.6 on 2019-10-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_manager', '0002_auto_20191003_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorsmodel',
            name='authors',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='authors',
            field=models.ManyToManyField(to='Books_manager.AuthorsModel'),
        ),
    ]
