# Generated by Django 2.2.6 on 2019-10-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books_manager', '0003_auto_20191003_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='authors',
            field=models.ManyToManyField(to='Books_manager.AuthorsModel', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='language',
            field=models.TextField(verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='page_count',
            field=models.SmallIntegerField(help_text='(only numbers)', verbose_name='Amount of pages'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='published_date',
            field=models.SmallIntegerField(help_text='(only year)', verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='imagelinksmodel',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='Books_manager.BookModel', verbose_name='Book id'),
        ),
        migrations.AlterField(
            model_name='imagelinksmodel',
            name='small_thumbnail',
            field=models.CharField(max_length=128, verbose_name='Link to small thumbnail'),
        ),
        migrations.AlterField(
            model_name='imagelinksmodel',
            name='thumbnail',
            field=models.CharField(max_length=128, verbose_name='Link to large thumbnail'),
        ),
        migrations.AlterField(
            model_name='industryidentifiersmodel',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='Books_manager.BookModel', verbose_name='Book id'),
        ),
        migrations.AlterField(
            model_name='industryidentifiersmodel',
            name='industry_identifiers_id',
            field=models.IntegerField(verbose_name='Industry id'),
        ),
        migrations.AlterField(
            model_name='industryidentifiersmodel',
            name='industry_identifiers_type',
            field=models.CharField(max_length=16, verbose_name='Industry id type'),
        ),
    ]
