# Generated by Django 2.2.6 on 2019-10-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_manager', '0004_auto_20191005_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='language',
            field=models.TextField(max_length=16, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='published_date',
            field=models.CharField(help_text='(max length 16', max_length=16, verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='imagelinksmodel',
            name='small_thumbnail',
            field=models.CharField(max_length=256, verbose_name='Link to small thumbnail'),
        ),
        migrations.AlterField(
            model_name='imagelinksmodel',
            name='thumbnail',
            field=models.CharField(max_length=256, verbose_name='Link to large thumbnail'),
        ),
        migrations.AlterField(
            model_name='industryidentifiersmodel',
            name='industry_identifiers_id',
            field=models.CharField(max_length=32, verbose_name='Industry id'),
        ),
        migrations.AlterField(
            model_name='industryidentifiersmodel',
            name='industry_identifiers_type',
            field=models.CharField(max_length=32, verbose_name='Industry id type'),
        ),
    ]
