# Generated by Django 2.2.6 on 2019-10-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_manager', '0005_auto_20191007_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='industryidentifiersmodel',
            name='industry_identifiers_id',
            field=models.CharField(max_length=64, verbose_name='Industry id'),
        ),
        migrations.AlterField(
            model_name='industryidentifiersmodel',
            name='industry_identifiers_type',
            field=models.CharField(max_length=64, verbose_name='Industry id type'),
        ),
    ]
